In [2]:
import numpy as np
import torch


a = torch.tensor([[1, 2, 3, 3], [1, 5, 4, 3]])
(a == 3).unsqueeze(-2)

tensor([[[False, False,  True,  True]],

        [[False, False, False,  True]]])

In [3]:
a[:, :-1]

tensor([[1, 2, 3],
        [1, 5, 4]])

In [11]:
(a != 3).data.sum()

tensor(5)

In [22]:
a = [i for i in range(5)]
a.reverse()
for i in a:
    print(i)

4
3
2
1
0


In [24]:
for i in range(5):
    print(i)

0
1
2
3
4


In [4]:
def subsequent_mask(size):
    "Mask out subsequent positions."
    attn_shape = (1, size, size)
    subsequent_mask = np.triu(np.ones(attn_shape), k=1).astype('uint8')
    return torch.from_numpy(subsequent_mask) == 0

subsequent_mask(3)

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])

In [10]:
from torch.autograd import Variable

b = torch.tensor([ [2,1,3], [2,3,1] ])
b_mask = (b != 4).unsqueeze(-2)
print(b_mask)
b_mask = b_mask & Variable(
            subsequent_mask(b.size(-1)).type_as(b_mask.data))

tensor([[[True, True, True]],

        [[True, True, True]]])


In [9]:
b.size(-1)

3

In [8]:
b_mask

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]],

        [[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])