In [1]:
import torch
import numpy as np

In [5]:
# Initializing a Tensor

# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# From a Numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# From another tensor
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [6]:
# With random or constant values
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
(rand_tensor, ones_tensor, zeros_tensor)

(tensor([[0.9112, 0.2848, 0.0986],
         [0.6838, 0.3540, 0.5749]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [7]:
# Attributes of a Tensor
tensor = torch.rand(3, 4)
(tensor.shape, tensor.dtype, tensor.device)

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [9]:
# Operations on Tensors

# Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), Each of these operations can be run on the GPU (at typically higher speeds than on a CPU).
# By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

tensor = torch.ones(4, 4)
(tensor[0], tensor[:, 0], tensor[..., -1])

# use torch.cat to concatenate a sequence of tensors along a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
# Atithmetic operations
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)

agg = tensor.sum()
agg_item = agg.item()
(agg_item, type(agg_item))

(16.0, float)

In [20]:
# Bridage with Numpy
t = torch.ones(5)
n = t.numpy()
(t, n)
t.add(1)

tensor([2., 2., 2., 2., 2.])