In [3]:
import torch

# Tensor Indexing

batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape)
print(x[:, 0].shape)
print(x[2, 0:10].shape)

# Fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols].shape)
print(x, x[rows, cols])
  
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0])

# More advanced indexing
print(torch.where(x > 5, x, x*2))
print(torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())
print(x.ndimension())
print(x.numel())

torch.Size([25])
torch.Size([10])
torch.Size([10])
tensor([2, 5, 8])
torch.Size([2])
tensor([[0.6909, 0.9456, 0.7938, 0.7650, 0.6677],
        [0.3143, 0.5171, 0.0626, 0.0822, 0.7551],
        [0.0851, 0.5007, 0.4483, 0.3757, 0.7563]]) tensor([0.7551, 0.6909])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [12]:
# Tensor Reshaping

x = torch.arange(9)
x_3x3 = x.view(3, 3)
x_3x3 = x.reshape(3, 3)
print(x_3x3)

y = x_3x3.t()
print(y)
print(y.contiguous().view(9))

x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

z = x1.view(-1)
print(z.shape)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

z = x.permute(0, 2, 1)
print(z)

print(torch.arange(10).unsqueeze(0).unsqueeze(1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])
tensor([[[9.1221e-01, 7.9471e-01],
         [4.6965e-01, 4.5051e-01],
         [4.4585e-01, 5.8750e-01],
         [9.4874e-01, 5.9346e-01],
         [6.4290e-01, 8.2842e-01]],

        [[9.4346e-01, 2.5689e-01],
         [1.5437e-01, 2.1360e-01],
         [8.8582e-01, 1.5868e-01],
         [5.9636e-01, 8.1810e-01],
         [6.0054e-01, 8.9860e-01]],

        [[1.6698e-01, 3.0599e-01],
         [1.7567e-01, 5.6118e-01],
         [2.5558e-01, 2.5322e-01],
         [5.9522e-01, 7.7477e-01],
         [7.3062e-01, 6.0195e-01]],

        [[9.0177e-01, 9.5169e-02],
         [3.1258e-01, 9.4349e-01],
         [2.3093e-01, 2.1573e-01],
         [4.8468e-01, 7.9795e-02],
         [4.5535e-01, 5.4669e-01]],

        [[1.4842e-01, 5.9976e-01],
         [3.0903e-01, 6.6310