In [23]:
import torch

# Tensor Math & Comparison Operations

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)

z2 = torch.add(x, y)
z = x + y
print(z)

# Subtraction
z = x - y
print(z)

# Division
z = torch.true_divide(x, y)
print(z)

# inplace operations
t = torch.zeros(3)
t.add_(x)
print(x)
t += x # t = t + x

# Exponentiation
z = x.pow(2)
print(z)

# Simple comparison
z = x > 0
z = x < 0
print(z)

# Matrix Multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
x3 = x1.mm(x2)

# matrix exponentiation
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))

# element wise mult
z = x * y
print(z)

# dot product
z = torch.dot(x, y)
print(z)

# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand(batch, m ,p)
out_bmm = torch.bmm(tensor1, tensor2)
print(tensor1, tensor2, out_bmm)

# Example of Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
print(z)

# Other useful tensor operations
print(x)
sum_x = torch.sum(x, dim=0)
print(sum_x)
values, indices = torch.max(x, dim=0)
print(values, indices)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
print(z)
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)
z = torch.eq(x, y)
torch.sort(y, dim=0, descending=False)

tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([False, False, False])
tensor([[2.9111, 3.4871, 3.8643, 4.3177, 2.3594],
        [2.8875, 3.4219, 3.9869, 4.2479, 2.4524],
        [3.9384, 4.2494, 4.7508, 5.4910, 2.8002],
        [2.1927, 2.4632, 2.8732, 3.1301, 1.7401],
        [2.2959, 2.5469, 3.0051, 3.1659, 1.6725]])
tensor([ 9, 16, 21])
tensor(46)
tensor([[[9.3631e-03, 7.8828e-01, 3.7822e-01,  ..., 7.3606e-01,
          3.2938e-01, 9.2400e-01],
         [4.5570e-01, 5.2127e-01, 5.0953e-01,  ..., 2.2695e-02,
          1.0865e-01, 4.3104e-01],
         [4.2337e-01, 3.4099e-01, 8.3240e-02,  ..., 5.8638e-01,
          4.3955e-01, 3.8536e-01],
         ...,
         [4.1015e-01, 1.9810e-01, 4.0496e-01,  ..., 1.8200e-01,
          4.7709e-01, 4.2732e-01],
         [9.5886e-01, 9.7663e-02, 3.8787e-01,  ..., 5.1353e-01,
          8.9851e-01, 7.5664e-01],
         [8.1078e-01, 2.0420e-01, 8.6078e-01,  ..., 6.3658e-02,
   

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))